# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 46da77b41cd053f89687b8739b957b10624a2d67a1d5aea0aff1abc5f932fae253b25d758338678981d0323a090d533c0286ccb552a61a058ca5cb256a6a914c

test:
  secret_key_base: 705bc830809345551851e16e0fb296471aabe269b644a66b65301d62490f295102ed9d2e3447cf7cd88c683070f0f5ab029c49847e92d7082922f135b0d1fa56

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
